spring.application.name=sistemaayd

# POSTGRESQL (variables de Railway, con valores por defecto para local)
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:tienda_repuestos}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false

server.port=${PORT:8080}
